"""
Response schemas for AI Generative Core API.

These Pydantic models define the structure of all API responses.
All providers MUST normalize their output to match these schemas,
ensuring consistent responses regardless of the underlying provider.
"""

from typing import Any, Optional

from pydantic import BaseModel, Field


class UsageInfo(BaseModel):
    """
    Token usage information returned by AI providers.

    Not all providers return all fields — hence all are optional.
    """

    prompt_tokens: Optional[int] = Field(
        default=None, description="Number of tokens in the prompt"
    )
    completion_tokens: Optional[int] = Field(
        default=None, description="Number of tokens in the completion"
    )
    total_tokens: Optional[int] = Field(
        default=None, description="Total tokens used (prompt + completion)"
    )


class GenerateResponse(BaseModel):
    """
    Standard response for text/multimodal generation.

    All providers normalize their output to this format.
    """

    output: str = Field(
        ..., description="Generated text output"
    )
    provider: str = Field(
        ..., description="Provider that generated the response"
    )
    model: str = Field(
        ..., description="Model that generated the response"
    )
    usage: Optional[UsageInfo] = Field(
        default=None, description="Token usage statistics"
    )
    metadata: Optional[dict[str, Any]] = Field(
        default=None, description="Additional provider-specific metadata"
    )


class ModelInfo(BaseModel):
    """
    Model metadata returned by GET /models endpoint.

    Describes a model's identity and capabilities.
    """

    name: str = Field(
        ..., description="Model name", examples=["llama3.2", "gemini-2.5-pro"]
    )
    provider: str = Field(
        ..., description="Provider name", examples=["ollama", "gemini"]
    )
    supports_text: bool = Field(
        ..., description="Whether the model supports text generation"
    )
    supports_image: bool = Field(
        ..., description="Whether the model supports image/multimodal input"
    )
    supports_embedding: bool = Field(
        ..., description="Whether the model supports vector embedding"
    )
    supports_reasoning: bool = Field(
        ..., description="Whether the model supports explicit reasoning mode"
    )


class EmbeddingResponse(BaseModel):
    """
    Response for vector embedding generation.
    """

    embedding: list[float] = Field(
        ..., description="Embedding vector as a list of floats"
    )
    provider: str = Field(
        ..., description="Provider that generated the embedding"
    )
    model: str = Field(
        ..., description="Model that generated the embedding"
    )


class ErrorResponse(BaseModel):
    """
    Standard error response format.

    Used for documenting error responses in Swagger UI.
    Actual error responses are generated by the exception handler in main.py.
    """

    error: str = Field(
        ..., description="Human-readable error message"
    )
    code: str = Field(
        ..., description="Machine-readable error code",
        examples=["PROVIDER_NOT_FOUND", "MODEL_NOT_FOUND"],
    )
    detail: Optional[str] = Field(
        default=None, description="Additional error details"
    )


class ChatResponse(BaseModel):
    """
    Response for POST /chat endpoint.

    Contains the AI-generated response and session metadata.
    """

    session_id: str = Field(
        ..., description="Session UUID (new or existing)"
    )
    output: str = Field(
        ..., description="Generated AI response text"
    )
    provider: str = Field(
        ..., description="Provider that generated the response"
    )
    model: str = Field(
        ..., description="Model that generated the response"
    )
    usage: Optional[UsageInfo] = Field(
        default=None, description="Token usage statistics"
    )
    turn_count: int = Field(
        ..., description="Total messages in this session"
    )
    metadata: Optional[dict[str, Any]] = Field(
        default=None, description="Additional provider-specific metadata"
    )


class ChatMessageSchema(BaseModel):
    """
    Schema for a single chat message in history.
    """

    role: str = Field(
        ..., description="Message role: user, assistant, or system"
    )
    content: str = Field(
        ..., description="Message text content"
    )
    timestamp: float = Field(
        ..., description="Unix timestamp when message was created"
    )
    model: Optional[str] = Field(
        default=None, description="Model used (only for assistant messages)"
    )


class ChatHistoryResponse(BaseModel):
    """
    Response for GET /chat/{session_id}/history endpoint.

    Contains full conversation history and session metadata.
    """

    session_id: str = Field(
        ..., description="Session UUID"
    )
    provider: str = Field(
        ..., description="Provider used for this session"
    )
    model: str = Field(
        ..., description="Model used for this session"
    )
    messages: list[ChatMessageSchema] = Field(
        ..., description="Ordered list of all messages in the session"
    )
    created_at: float = Field(
        ..., description="Unix timestamp when session was created"
    )
    last_active: float = Field(
        ..., description="Unix timestamp of last activity"
    )
    turn_count: int = Field(
        ..., description="Total messages in this session"
    )


class CacheStatsResponse(BaseModel):
    """Response for GET /cache/stats endpoint."""

    total_hits: int = Field(
        ..., description="Total number of cache hits"
    )
    total_misses: int = Field(
        ..., description="Total number of cache misses"
    )
    hit_rate: float = Field(
        ..., description="Cache hit rate (0.0 to 1.0)"
    )
    current_size: int = Field(
        ..., description="Current number of entries in cache"
    )
    max_size: int = Field(
        ..., description="Maximum cache capacity"
    )
    evictions: int = Field(
        ..., description="Total LRU evictions performed"
    )


class CacheClearResponse(BaseModel):
    """Response for DELETE /cache endpoint."""

    message: str = Field(
        ..., description="Confirmation message"
    )
    entries_removed: int = Field(
        ..., description="Number of entries that were cleared"
    )


class ModelInfoWithAvailability(ModelInfo):
    """Model metadata with current provider availability status."""

    available: bool = Field(
        ..., description="True if the underlying provider is UP or DEGRADED"
    )


class ProviderHealthDetail(BaseModel):
    """Health status detail for a single provider."""

    status: str = Field(
        ..., description="Provider status: up, down, or degraded"
    )
    last_check: Optional[str] = Field(
        default=None, description="ISO timestamp of last health check"
    )
    last_success: Optional[str] = Field(
        default=None, description="ISO timestamp of last successful check"
    )
    latency_ms: Optional[float] = Field(
        default=None, description="Last probe latency in milliseconds"
    )
    consecutive_failures: int = Field(
        default=0, description="Number of consecutive probe failures"
    )
    error: Optional[str] = Field(
        default=None, description="Last error message"
    )


class HealthSummary(BaseModel):
    """Summary counts of provider health statuses."""

    total: int = Field(..., description="Total number of providers")
    up: int = Field(..., description="Providers in UP status")
    down: int = Field(..., description="Providers in DOWN status")
    degraded: int = Field(..., description="Providers in DEGRADED status")


class HealthProvidersResponse(BaseModel):
    """Response for GET /health/providers endpoint."""

    status: str = Field(
        ..., description="Overall system status: healthy, degraded, or unhealthy"
    )
    providers: dict[str, ProviderHealthDetail] = Field(
        ..., description="Per-provider health details"
    )
    summary: HealthSummary = Field(
        ..., description="Summary counts"
    )


class BatchGenerateResult(BaseModel):
    """Result for a single item in batch generate."""

    index: int = Field(..., description="Original index in request")
    status: str = Field(..., description="'success' or 'error'")
    output: Optional[str] = Field(
        default=None, description="Generated text (on success)"
    )
    usage: Optional[UsageInfo] = Field(
        default=None, description="Token usage (on success)"
    )
    error: Optional[str] = Field(
        default=None, description="Error message (on failure)"
    )
    cached: bool = Field(
        default=False, description="Whether result was from cache"
    )


class BatchGenerateResponse(BaseModel):
    """Response for POST /batch/generate."""

    provider: str = Field(..., description="Provider used")
    model: str = Field(..., description="Model used")
    total: int = Field(..., description="Total items submitted")
    succeeded: int = Field(..., description="Items that succeeded")
    failed: int = Field(..., description="Items that failed")
    results: list[BatchGenerateResult] = Field(
        ..., description="Per-item results (ordered by index)"
    )


class BatchEmbeddingResult(BaseModel):
    """Result for a single item in batch embedding."""

    index: int = Field(..., description="Original index in request")
    status: str = Field(..., description="'success' or 'error'")
    embedding: Optional[list[float]] = Field(
        default=None, description="Embedding vector (on success)"
    )
    error: Optional[str] = Field(
        default=None, description="Error message (on failure)"
    )
    cached: bool = Field(
        default=False, description="Whether result was from cache"
    )


class BatchEmbeddingResponse(BaseModel):
    """Response for POST /batch/embedding."""

    provider: str = Field(..., description="Provider used")
    model: str = Field(..., description="Model used")
    total: int = Field(..., description="Total items submitted")
    succeeded: int = Field(..., description="Items that succeeded")
    failed: int = Field(..., description="Items that failed")
    results: list[BatchEmbeddingResult] = Field(
        ..., description="Per-item results (ordered by index)"
    )
